"use client";

import { useState } from "react";

const REQUIREMENTS = [
  {
    category: "Authentication & Org Connection",
    items: [
      "Salesforce OAuth 2.0 Web Server Flow (no password stored in app)",
      "Connected App configuration via admin-supplied Client ID + Secret",
      "Encrypted httpOnly session cookie (iron-session v8)",
      "Disconnect / re-connect flow",
      "Org connection status indicator in header",
    ],
  },
  {
    category: "Work Items List",
    items: [
      "Query AgentWork records via Salesforce REST API v62.0",
      "Configurable day-range filter (24h / 7d / 30d), persisted in localStorage",
      "Sortable table: Ref, Case, Contact, Phone, Channel, Queue, Agent, Routing Type, Status, Created, Time to Accept",
      "Live search across channel, queue, agent, status, work item ref",
      "Customer enrichment: Case → CaseNumber + Contact.Name + phone; VoiceCall → FromPhoneNumber; MessagingSession → end user name",
      "Horizontally scrollable table on narrow viewports",
      "Green ✓ validated badge and red ✗ misrouted badge on work item rows",
    ],
  },
  {
    category: "Routing Chain (Multi-Leg)",
    items: [
      "RoutingChain: all AgentWork records for one conversation, ordered chronologically by CreatedDate",
      "getRoutingChain(): anchor query → WorkItemId → all sibling AgentWork records → batch AgentWorkSkill → resolve queue names → resolve customer info once",
      "RoutingLeg: flat shape per AgentWork record with isAI, agentName, queueName, channelLabel, routingType, timeToAcceptSeconds, flags, agentSkills",
      "AI detection: User.Name === 'Automated Process' or User is null",
      "Chain-level flags: escalation detected, BYOT single-leg caveat",
      "analyzeChain() / analyzeLeg(): deterministic flag and warning generation on flat leg shape",
      "narrateChain(): safe payload (no customer fields) → Claude narration → deterministic fallback",
      "legToTrace() adapter: derives RoutingTrace from a leg + chain for backward compat with DataPanel and SubwayMap",
    ],
  },
  {
    category: "Routing Chain Timeline (Accordion UI)",
    items: [
      "Vertical timeline: colored dot per node type connected by a line",
      "ChainNode types: channel-entry, omniflow (placeholder), agent-work, escalation (placeholder)",
      "Node color palette: channel-entry = blue, omniflow = pink, escalation = red, AI agent = blue, human agent = blue",
      "Collapsed state: icon + event type + name + timestamp in one line",
      "Expanded state: full detail grid, per-leg flags, agent skills",
      "Entry AgentWork node starts expanded; all others collapsed — hints to users that nodes are clickable",
      "Expand All / Collapse All toggle",
      "OmniFlow placeholder: inserted when routing type or work item type suggests a flow ran before AgentWork was created; Phase 3 badge",
      "Escalation placeholder: inserted at each AI→human transition; shows datetime if available; Phase 3 badge",
    ],
  },
  {
    category: "Trace Page Header",
    items: [
      "Work item title: Case {number} if available, otherwise {workItemType} ···{last-6 of WorkItemId}",
      "Pill strip: channel · phone/descriptor · N legs (if >1) · escalating agent (if escalated) · outcome · final agent · timestamp",
      "Outcome pill: Escalated (violet), Active (green), Assigned (blue), or status fallback",
      "Warning icon (⚠) in pill strip — hover reveals a tooltip with a one-liner per unique warning — replaces banner",
      "Warning tooltip summaries: external routing, BYOT, skill mismatch, capacity — short plain-English labels",
    ],
  },
  {
    category: "Correction & Suggestion Flow",
    items: [
      "Correction input: intended agent/queue + optional free-text rationale",
      "Config suggestion generated by Claude: specific Salesforce setting to change",
      "Deterministic fallback suggestion when no AI key is configured",
      "Verdict buttons: 👍 → confetti + mark validated; 👎 → mark flagged → show CorrectionPanel → SuggestionPanel",
      "Validated and flagged IDs persisted in localStorage (mutually exclusive)",
      "Confetti animation on 👍 verdict",
    ],
  },
  {
    category: "OmniFlow Diagram (Phase 3)",
    items: [
      "GET /api/flow?agentWorkId=X — fetches all active RoutingFlow versions via Tooling API, parses Metadata, infers path for the given AgentWork record",
      "lib/flow-types.ts — raw Salesforce Flow Metadata interfaces (FlowActionCall, FlowDecision, FlowRule, FlowStart) and graph types (FlowNode, FlowEdge, ParsedFlowGraph, FlowGraphWithPath)",
      "lib/flow-graph.ts — parseFlowGraph(): synthetic __start__ node, wires via startElementReference or start.connector.targetReference, processes actionCalls and decisions into nodes/edges",
      "inferPath(): BFS from __start__ to matched routeWork node; match strategies: queue ID match (high confidence), routing type match (medium), single-routeWork fallback (low)",
      "OmniFlowDiagram.tsx — ReactFlow v11.11.4 client-only component (ssr: false dynamic import); custom actionNode, startNode, decisionNode types defined outside component to avoid ReactFlow warnings",
      "BFS layered layout: first-visit BFS assigns layer depth, nodes centered per layer; NODE_W=168 NODE_H=52 DIAMOND_W=80 H_GAP=48 V_GAP=80",
      "On-path nodes: brand-500 blue borders; terminal routeWork node: green-500; off-path nodes: slate border + opacity-60",
      "Diamond decision nodes via CSS rotate(45deg) with counter-rotated text label overlay",
      "Confidence badge: 'Inferred path · {confidence} confidence' or 'Full flow — path not inferred'",
      "Routing Type in InboundBox sourced from matched flow node's routingType inputParameter (not AgentWork.RoutingType, which is always 'QueueBased' even for Copilot/Flow-routed items)",
      "Agent name in RoutingResultsBox sourced from matched routeWork node's copilotLabel inputParameter when present (e.g. 'Omega (AI)'), falling back to User.Name",
      "Flow Metadata cached 1 hour via Next.js fetch revalidate — flow definitions change rarely",
      "sfToolingGet<T>: direct REST GET against Tooling API for sObject records (e.g. /sobjects/Flow/{id} returns full Metadata field)",
      "sfToolingQuery<T>: SOQL via Tooling API endpoint — required for Flow and other Setup objects",
      "Key Salesforce discovery: ProcessType field lives on the Flow (version) object, correct value is 'RoutingFlow' — not on FlowDefinition, not 'OmniChannelFlow'",
      "OmniFlowSkeleton defined before dynamic() call — loading fallback prop references it by closure, so ordering matters",
      "flowData drives both the diagram and field enrichment in InboundBox and RoutingResultsBox; showFlowBlock hides the diagram section entirely if no matching RoutingFlow is found",
    ],
  },
  {
    category: "RouteMap (Org Overview, Beta)",
    items: [
      "Org-wide stat cards: Service Channels, Queues, Skills, Active Users",
      "Hover tooltips on each stat card linking to the relevant Setup path",
      "Shows — (not 0) for objects unavailable via REST/Tooling API",
      "AI-generated routing narrative for the org",
      "SubwayMap: legacy visual pushed to bottom of trace page, collapsible, default collapsed",
    ],
  },
  {
    category: "Privacy & Data Guard",
    items: [
      "Customer data (names, phone numbers, case numbers) displayed in admin's browser only — same as a Salesforce list view",
      "data-guard.ts strips all customer fields before any Claude API call — enforced at the module boundary",
      "Agent name, username, and routing metadata are safe to send to Claude (admins are the assumed users)",
      "No customer data is stored in any database or log file",
      "Data & Privacy page documents exactly what is and is not sent, honestly",
    ],
  },
  {
    category: "UI & Navigation",
    items: [
      "Dark / light mode toggle, persisted in localStorage, no flash on load",
      "Header: dark gradient, road-sign SVG logo, RouteCause wordmark, v1 badge, Live indicator",
      "Footer: About, Omni-Channel, Made With SF + Claude, Data & Privacy links",
      "Responsive layout with max-w constraints",
      "Salesforce Omni-Channel reference page with overview, docs links, best practices",
      "About page with Connected App setup guide and feature descriptions",
    ],
  },
];

const ONE_PASS_PROMPT = `Build a Next.js 14 App Router web application called "RouteCause" — a Salesforce Omni-Channel routing explainer and post-incident audit tool.

## Core purpose
Connect to a Salesforce org, show recent AgentWork records (routing decisions), click one to see a full routing chain in plain English, flag it if wrong, and get a concrete Salesforce config change suggestion. For items that passed through an Omni-Channel Flow, render an interactive diagram of the flow with the inferred path highlighted.

## Tech stack
- Next.js 14 App Router, TypeScript, Tailwind CSS (darkMode: "class")
- iron-session v8 for encrypted httpOnly cookie sessions
- Salesforce REST API v62.0 + Tooling API v62.0
- ReactFlow v11.11.4 for the OmniFlow diagram (client-only, ssr: false)
- Anthropic Claude claude-sonnet-4-6 for narration and suggestions — deterministic fallback if no key

## Authentication
OAuth 2.0 Web Server Flow. Admin supplies instanceUrl, clientId, clientSecret on /connect. App redirects to Salesforce auth, receives callback at /api/auth/callback, stores accessToken + instanceUrl in iron-session. ThemeToggle persists rc-theme to localStorage; inline <script> in <head> applies class before paint to prevent flash.

## Hard privacy rule
Customer data (case numbers, names, phone numbers, message content) may be displayed in the admin's browser but must NEVER be sent to Claude or any external API. A data-guard.ts module strips all customer fields before any AI call. Agent name, username, and routing metadata are safe to send — admins are the assumed users. This constraint shapes every API payload.

## Core data model

### RoutingLeg (one AgentWork record)
Fields: agentWorkId, legIndex, isAI (User.Name === "Automated Process" || User == null), agentName, agentUsername, queueName, channelLabel, routingModel, routingType, status, capacityWeight, capacityPercentage, createdDate, acceptDateTime, timeToAcceptSeconds, routingConfigPriority, agentSkills[], requiredSkills[], flags[]

### RoutingChain (full conversation)
Fields: entryAgentWorkId, sfWorkItemId, workItemType, instanceUrl, customer (browser-only), legs[], chainFlags[]

### getRoutingChain() strategy
1. Anchor query to get WorkItemId from clicked AgentWork
2. Query ALL AgentWork WHERE WorkItemId = X ORDER BY CreatedDate ASC
3. Batch-fetch AgentWorkSkill for all leg IDs in one query
4. Resolve queue names for all unique OriginalQueueIds in one query
5. Resolve customer info once (same WorkItemId for all legs)
6. Build chainFlags: escalation detected (AI→human transition), BYOT caveat (Voice Call + single AI leg)

### legToTrace() adapter
Derives a RoutingTrace from a RoutingLeg + RoutingChain for backward compat with DataPanel and SubwayMap.

## Routing Chain accordion UI (trace page)
The chain IS the map — a vertical event timeline replacing a separate diagram.

### ChainNode types (in order)
1. channel-entry — always first; shows channel label, phone if available, timestamp
2. omniflow — placeholder inserted when workItemType is Voice Call / Messaging Session or routingType === OmniFlow; Phase 3 badge
3. agent-work — one per RoutingLeg; collapsed = agent + queue + timing + routing type badge; expanded = detail grid + flags + skills
4. escalation — placeholder inserted at each AI→human transition; shows datetime; Phase 3 badge

### Node color palette (dot on timeline + card border/bg)
- channel-entry: blue dot, blue-100 card
- omniflow: pink dot, pink-100 card
- escalation: red dot, red-100 card
- agent-work (AI): blue dot, blue-100 card
- agent-work (human): blue dot, blue-100 card

### Behavior
- Entry AgentWork node starts expanded (hints to users that nodes are clickable)
- All others collapsed by default
- Expand All / Collapse All toggle

## Trace page layout (RouteMap component)
The trace page renders a vertical RouteMap of three blocks:
1. Inbound Interaction box (channel, routing type, platform key, routing config)
2. OmniFlow diagram — shown only when a matching RoutingFlow is found (or loading)
3. Routing Results box — one per leg, with queue, agent, timing, capacity

Routing Type in the Inbound box is sourced from the matched flow node's routingType inputParameter — not AgentWork.RoutingType, which is always "QueueBased" even for Copilot-routed items. When a flow match exists, shows "{routingType} · via {flowLabel}".

Agent name in Routing Results is sourced from the matched routeWork node's copilotLabel inputParameter when present (shows "Omega (AI)"), falling back to User.Name.

## OmniFlow diagram (Phase 3)
GET /api/flow?agentWorkId=X:
1. Fetch AgentWork to get OriginalQueueId and RoutingType
2. Fetch all active RoutingFlow versions via Tooling API (ProcessType = 'RoutingFlow', Status = 'Active'), deduped to latest per DefinitionId
3. For each, fetch /tooling/sobjects/Flow/{id} (cached 1h) — returns full Metadata field
4. parseFlowGraph(metadata): synthetic __start__ node, wire via startElementReference or start.connector.targetReference, process actionCalls + decisions into FlowNode/FlowEdge arrays
5. inferPath(): BFS from __start__ to matched routeWork node; match strategies: queue ID match (high confidence), routing type match (medium), single-routeWork fallback (low)
6. Return first match as { graph: FlowGraphWithPath, flowDeveloperName, flowLabel }

### FlowNode kinds
start | checkAvailability | routeWork | playPrompt | screenPop | decision | other

### routeWork node carries
queueId, queueLabel, routingType, copilotLabel (from inputParameters)

### OmniFlowDiagram component (ReactFlow v11)
- ssr: false dynamic import — ReactFlow requires browser APIs
- OmniFlowSkeleton defined BEFORE dynamic() call — loading callback closes over it
- Custom node types (actionNode, startNode, decisionNode) defined OUTSIDE component to avoid ReactFlow re-registration warnings
- BFS layered layout: first-visit BFS assigns layer depth; nodes centered per layer
  NODE_W=168, NODE_H=52, DIAMOND_W=80, H_GAP=48, V_GAP=80
- On-path nodes: brand-500 blue border; terminal routeWork: green-500; off-path: slate + opacity-60
- Decision nodes: CSS rotate(45deg) diamond with counter-rotated text label
- Confidence badge: "Inferred path · {confidence} confidence" or "Full flow — path not inferred"

### Key Salesforce Tooling API facts (hard-won)
- ProcessType field is on the Flow (version) object, NOT FlowDefinition — correct value is 'RoutingFlow'
- FlowElement and FlowConnector are NOT queryable via SOQL — get full Metadata via REST GET on /tooling/sobjects/Flow/{id}
- AgentWork.RoutingType is always 'QueueBased' even for Copilot/Flow-routed items — do NOT gate flow fetch on this field

## Trace page header
- h1: "Case {number}" if available, else "{workItemType} ···{last-6 of sfWorkItemId}"
- Pill strip: channel · phone/descriptor · N legs (if >1) · escalating agent name (if escalated) · outcome pill · final agent · timestamp
- Outcome pill: Escalated (violet), Active (green), Assigned (blue), or status fallback
- Warning icon (⚠) as last pill — hover tooltip shows one-liner per unique warning — no banners

## Pages & routes
- /connect — OAuth connect form
- /work-items — sortable, searchable AgentWork list. Day-range filter (24h/7d/30d) → localStorage rc-days-filter. Green ✓ / red ✗ badges from rc-validations / rc-flagged.
- /trace/[id] — full trace page using RoutingChain. RouteMap (Inbound + OmniFlow diagram + Routing Results). Accordion timeline. Pill strip header. Full Explanation (collapsible). Raw data panel with clickable SF record links. Verdict buttons. SubwayMap at bottom (collapsible, default collapsed).
- /synopsis — org-wide stat cards (channels, queues, skills, users) with hover tooltips for Setup paths. Shows — for objects not queryable via REST. AI narration of org config.
- /about — what RouteCause does, Connected App setup guide, beta features.
- /data-privacy — full honest data handling disclosure.
- /omni-channel — Omni-Channel overview and best practices reference.
- /made-with — this page (requirements + one-pass prompt).
- /api/trace?id= — GET, returns { chain, narration }
- /api/flow?agentWorkId= — GET, returns { graph: FlowGraphWithPath, flowDeveloperName, flowLabel } or { notFound, reason }
- /api/work-items — GET, returns WorkItemRow[] with customer enrichment
- /api/suggest — POST, returns ConfigSuggestion
- /api/synopsis — GET, returns synopsis data + narration
- /api/org — GET, returns { connected, label }
- /api/auth/* — OAuth connect / callback / disconnect

## Key Salesforce API constraints
- RoutingConfig, ServicePresenceConfig, QueueRoutingConfig are NOT queryable via REST in most orgs — show — not 0
- ServiceChannel has no RoutingModel field — that lives on RoutingConfig
- AgentWorkSkill has no relationshipName — query it separately, never as a subquery
- VoiceCall has no Status column — do not query it
- Group WHERE Type = 'Queue' returns ALL queues, not just Omni-Channel queues
- AgentWork.RoutingType is always 'QueueBased' even for flow-routed items — never use it to gate flow lookup

## UI details
- Header: dark gradient (slate-900 → brand-700 → slate-900), road-sign SVG logo, RouteCause wordmark, v1 badge, Live dot, ThemeToggle
- All dark: variants required everywhere
- Work items table: overflow-x-auto wrapper, min-w-max on table
- Confetti: canvas-based, fires on 👍 verdict
- Validated/flagged IDs mutually exclusive; both stored in localStorage`;

export default function MadeWithPage() {
  const [copied, setCopied] = useState(false);

  function copyPrompt() {
    navigator.clipboard.writeText(ONE_PASS_PROMPT).then(() => {
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    });
  }

  return (
    <div className="max-w-4xl mx-auto py-4 space-y-10">
      <div>
        <h1 className="text-2xl font-black text-slate-900 dark:text-white mb-1">
          Made with Salesforce + Claude
        </h1>
        <p className="text-slate-500 dark:text-slate-400 text-sm leading-relaxed max-w-2xl">
          RouteCause was built collaboratively — someone who knew exactly what
          the problem was, working with Claude to design and build it. The
          requirements, decisions, and constraints came from real experience
          with Salesforce Omni-Channel; the code came from the conversation.
        </p>
      </div>

      {/* How it was built */}
      <section className="bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-700 rounded-xl p-6 space-y-3">
        <div className="flex items-center gap-2 mb-2">
          <div className="w-1 h-4 bg-brand-500 rounded-full" />
          <h2 className="text-xs font-bold uppercase tracking-widest text-slate-500 dark:text-slate-400 font-mono">
            How it was built
          </h2>
        </div>
        <p className="text-sm text-slate-700 dark:text-slate-300 leading-relaxed">
          This app didn't start with a spec doc. It started with a problem:{" "}
          <em>why did this work item route to that agent?</em> Salesforce
          doesn't have a native tool to answer that question in plain English,
          so we built one.
        </p>
        <p className="text-sm text-slate-700 dark:text-slate-300 leading-relaxed">
          The architecture, data model, privacy constraints, and UX decisions
          all came from hands-on Salesforce experience. Claude translated those
          into working Next.js code, caught API limitations (like which objects
          aren't queryable via REST), and iterated on the design through
          conversation — no Figma file, no PRD, just back-and-forth.
        </p>
        <p className="text-sm text-slate-700 dark:text-slate-300 leading-relaxed">
          The hard rule —{" "}
          <strong className="text-slate-900 dark:text-white">
            customer data never leaves the org or reaches any AI
          </strong>{" "}
          — was set on day one and enforced in every subsequent decision. That
          constraint shaped the data-guard layer, the privacy page, and which
          fields are included in every API payload.
        </p>
      </section>

      {/* Requirements */}
      <section className="space-y-6">
        <div className="flex items-center gap-2">
          <div className="w-1 h-4 bg-brand-500 rounded-full" />
          <h2 className="text-xs font-bold uppercase tracking-widest text-slate-500 dark:text-slate-400 font-mono">
            Full Requirements
          </h2>
        </div>

        {REQUIREMENTS.map(({ category, items }) => (
          <div
            key={category}
            className="bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-700 rounded-xl p-6"
          >
            <h3 className="text-sm font-bold text-slate-800 dark:text-slate-200 mb-3">
              {category}
            </h3>
            <ul className="space-y-1.5">
              {items.map((item, i) => (
                <li
                  key={i}
                  className="flex gap-2 text-sm text-slate-600 dark:text-slate-400"
                >
                  <span className="text-brand-400 shrink-0 mt-0.5">–</span>
                  <span>{item}</span>
                </li>
              ))}
            </ul>
          </div>
        ))}
      </section>

      {/* One-pass prompt */}
      <section className="space-y-4">
        <div className="flex items-center gap-2">
          <div className="w-1 h-4 bg-amber-500 rounded-full" />
          <h2 className="text-xs font-bold uppercase tracking-widest text-slate-500 dark:text-slate-400 font-mono">
            One-Pass Build Prompt
          </h2>
        </div>
        <p className="text-sm text-slate-500 dark:text-slate-400">
          If you wanted to recreate this app from scratch in a single prompt to
          Claude, this is how you would describe it.
        </p>
        <div className="relative bg-slate-900 dark:bg-slate-950 border border-slate-700 rounded-xl overflow-hidden">
          <div className="flex items-center justify-between px-5 py-3 border-b border-slate-700">
            <span className="text-xs text-slate-500 font-mono">prompt</span>
            <button
              onClick={copyPrompt}
              className="text-xs font-mono px-3 py-1 rounded-lg bg-slate-700 hover:bg-slate-600 text-slate-300 hover:text-white transition-colors"
            >
              {copied ? "✓ Copied" : "Copy"}
            </button>
          </div>
          <div className="p-5 overflow-x-auto">
            <pre className="text-xs text-slate-300 leading-relaxed whitespace-pre-wrap font-mono">
              {ONE_PASS_PROMPT}
            </pre>
          </div>
        </div>
      </section>
    </div>
  );
}
